# Generated by Django 4.2.7 on 2024-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_rustdesdevice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rustdesdevice",
            options={
                "ordering": ("-rid",),
                "verbose_name": "设备",
                "verbose_name_plural": "设备列表",
            },
        ),
        migrations.AlterModelOptions(
            name="rustdeskpeer",
            options={
                "ordering": ("-username",),
                "verbose_name": "Peers",
                "verbose_name_plural": "Peers列表",
            },
        ),
        migrations.AlterModelOptions(
            name="rustdesktag",
            options={
                "ordering": ("-uid",),
                "verbose_name": "Tags",
                "verbose_name_plural": "Tags列表",
            },
        ),
        migrations.AlterModelOptions(
            name="rustdesktoken",
            options={
                "ordering": ("-username",),
                "verbose_name": "Token",
                "verbose_name_plural": "Token列表",
            },
        ),
        migrations.AlterModelOptions(
            name="sharelink",
            options={
                "ordering": ("-create_time",),
                "verbose_name": "分享链接",
                "verbose_name_plural": "链接列表",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": (
                    ("view_task", "Can see available tasks"),
                    ("change_task_status", "Can change the status of tasks"),
                    ("close_task", "Can remove a task by setting its status as closed"),
                ),
                "verbose_name": "用户",
                "verbose_name_plural": "用户列表",
            },
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="设备注册时间"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="hostname",
            field=models.CharField(max_length=100, verbose_name="主机名"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="memory",
            field=models.CharField(max_length=100, verbose_name="内存"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="os",
            field=models.CharField(max_length=100, verbose_name="操作系统"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="rid",
            field=models.CharField(blank=True, max_length=60, verbose_name="客户端ID"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name="系统用户名"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="version",
            field=models.CharField(max_length=100, verbose_name="客户端版本"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="alias",
            field=models.CharField(max_length=30, verbose_name="别名"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="hostname",
            field=models.CharField(max_length=30, verbose_name="操作系统名"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="platform",
            field=models.CharField(max_length=30, verbose_name="平台"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="rhash",
            field=models.CharField(max_length=60, verbose_name="设备链接密码"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="rid",
            field=models.CharField(max_length=60, verbose_name="客户端ID"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="tags",
            field=models.CharField(max_length=30, verbose_name="标签"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="username",
            field=models.CharField(max_length=20, verbose_name="系统用户名"),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="tag_color",
            field=models.CharField(blank=True, max_length=60, verbose_name="标签颜色"),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="tag_name",
            field=models.CharField(max_length=60, verbose_name="标签名称"),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="所属用户ID"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="access_token",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="access_token"
            ),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="username",
            field=models.CharField(max_length=20, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="uuid",
            field=models.CharField(max_length=60, verbose_name="uuid"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="是否过期"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="是否使用"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="peers",
            field=models.CharField(max_length=20, verbose_name="机器ID列表"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="shash",
            field=models.CharField(max_length=60, verbose_name="链接Key"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="deviceInfo",
            field=models.TextField(blank=True, verbose_name="登录信息:"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="是否管理员"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="用户名"),
        ),
    ]
