# Generated by Django 5.1 on 2024-08-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rustdesdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdesdevice',
            name='owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属用户'),
        ),
    ]
